const Constants = {
    BY_ARRIVE: 'BY_ARRIVE',
    BY_DEPART: 'BY_DEPART',
    BY_DELAY: 'BY_DELAY',
    SEARCH_BY_NUMBER_FLIGHT: 'SEARCH_BY_NUMBER_FLIGHT',
    LOAD_FLIGHT: 'LOAD_FLIGHT',
    LOAD_STATION: 'LOAD_STATION',
    LOAD_CARRIER: 'LOAD_CARRIER',
    REMOVE_FLIGHT: 'REMOVE_FLIGHT',
    REMOVE_STATION: 'REMOVE_STATION',
    REMOVE_CARRIER: 'REMOVE_CARRIER',
    LOAD_BOARD: 'LOAD_BOARD',
    FILTER_BY_DELAY: 'FILTER_BY_DELAY',
};

export default Constants;
